CREATE PROCEDURE [dbo].[SP_filtroVariable_4]
	@COD_CONSULTA INT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @TOTAL INT
	DECLARE @PARCIAL INT
	DECLARE @CONSULTA NVARCHAR(MAX)

	SET @TOTAL=(SELECT TOP 1 ID FROM TEST ORDER BY ID DESC)
	SET @PARCIAL = @TOTAL/4

	SET @CONSULTA = CASE
				WHEN @COD_CONSULTA=1 THEN 'SELECT * FROM TEST WHERE ID BETWEEN 1 AND '+CAST(@PARCIAL AS NVARCHAR(5))
				WHEN @COD_CONSULTA=2 THEN 'SELECT * FROM TEST WHERE ID BETWEEN '+CAST(@PARCIAL+1 AS NVARCHAR(5))+' AND '+CAST(@PARCIAL*2 AS NVARCHAR(5))
				WHEN @COD_CONSULTA=3 THEN 'SELECT * FROM TEST WHERE ID BETWEEN '+CAST(@PARCIAL*2+1 AS NVARCHAR(5))+' AND '+CAST(@PARCIAL*3 AS NVARCHAR(5))
				WHEN @COD_CONSULTA=4 THEN 'SELECT * FROM TEST WHERE ID BETWEEN '+CAST(@PARCIAL*3+1 AS NVARCHAR(5))+' AND '+CAST(@TOTAL AS NVARCHAR(5))
	END

	PRINT @CONSULTA
	EXEC sp_executesql @CONSULTA
END