DECLARE @CONTENIDO NVARCHAR(500) = 'Ejemplo de cantidad de palabras'



SELECT	@CONTENIDO AS 'FRASE_COMPLETA'
		,LEFT(@CONTENIDO, CHARINDEX(' ', @CONTENIDO) - 1) AS 'PRIMERA_PALABRA'
		,LEFT(@CONTENIDO, CHARINDEX(' ', @CONTENIDO, CHARINDEX(' ', @CONTENIDO) + 1) - 1) AS 'PRIMERAS_2'
		,CASE
	        WHEN CHARINDEX(' ', @CONTENIDO, CHARINDEX(' ', @CONTENIDO, CHARINDEX(' ', @CONTENIDO) + 1) + 1) > 0 THEN
		        LEFT(@CONTENIDO, CHARINDEX(' ', @CONTENIDO, CHARINDEX(' ', @CONTENIDO, CHARINDEX(' ', @CONTENIDO) + 1) + 1) - 1)
		ELSE
            @CONTENIDO 
		END AS 'PRIMERAS_3'
